### ISSUE TITLE
Question about single-cell RNA-seq data

### ISSUE THREAD

**Issue by sunshine-lp0** [mikelove/rnaseqDTU#3]
Dear Michael I. Love,

I used single-cell RNA-seq data to run the rnaseqDTU workflow. Everything is fine until running DEXSeq. The process gets extremely slow and I think the reason is that I have too many cells (500cells). Do you think rnaseqDTU is suitable for single-cell RNA-seq data?

Thanks very much! Look forward for your reply:)

**Comment by mikelove** [comment]
Good question, I haven't run the DTU analysis on single cells.

I don't maintain and am not an author of DEXSeq, but I wonder if you can take advantage of the new underlying code for improving DESeq2 fitting speed:

```
fitType="glmGamPoi"
```

See the second bullet here:

https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#recommendations-for-single-cell-analysis

I'm not sure if it's possible, but if it were, the speed with glmGamPoi is much faster:

https://github.com/const-ae/glmGamPoi#benchmark

**Comment by sunshine-lp0** [comment]
Thank you very much!

**Comment by kvittingseerup** [comment]
That is very interesting! Have you benchmarked DEXSeq on bulk data with the `fitType="glmGamPoi"`?

**Comment by mikelove** [comment]
It should be greatly increased, but I'm not sure if it is integrated yet.

I think they would need to pass `fitType` along here (or use `...`):

https://github.com/areyesq89/DEXSeq/blob/master/R/core.R#L259-L275
