### ISSUE TITLE
Results from rnaseqDTU workflow not what they should be?

### ISSUE THREAD

**Issue by pegahabyaneh** [mikelove/rnaseqDTU#4]
Dear Michael Love,

I've been following the "Swimming downstream" DTU analysis tutorial using the salmon.tgz data set from Zenodo, but my results stop matching those from the tutorial after I create a dmDSdata object and filter it. Creating the object works fine, but after filtering and estimating model parameters, the results tables I produce show different genes and transcripts from the ones shown in the tutorial. For instance, in the workflow I should be getting the following results:

head(results)
              gene_id        lr   df     pvalue   adj_pvalue
1 ENSG00000000457.13  1.493561   4 8.277814e-01 9.120246e-01
2 ENSG00000000460.16  1.068294   3 7.847330e-01 9.101892e-01
3 ENSG00000000938.12  4.366806   2 1.126575e-01 2.750169e-01
4 ENSG00000001084.11  1.630085   3 6.525877e-01 8.643316e-01
5 ENSG00000001167.14  28.402587  1 9.853354e-08 5.007113e-07
6 ENSG00000001461.16  9.815460   1 1.730510e-03 6.732766e-03

However, this is what I see in the R console:

head(results)
              gene_id         lr   df     pvalue   adj_pvalue
1 ENSG00000237094.12  52.9721358  1 3.383138e-13 2.532227e-12
2 ENSG00000237491.8   2.7403807   1 9.784145e-02 3.179847e-01
3 ENSG00000228794.8   6.9271154   2 3.131814e-02 1.330626e-01
4 ENSG00000187961.13  0.9699384   2 6.157162e-01 8.934371e-01
5 ENSG00000217801.9   0.2262070   1 6.343506e-01 8.934371e-01
6 ENSG00000131591.17  30.4292202  1 3.462727e-08 2.136131e-07

I have tried switching from R version 4.1 and Bioconductor version 13.3 to the older ones used in the tutorial, but I got error messages when trying to download the rnaseqDTU package which said it was not available to older versions of Bioconductor. As I use RStudio, I also tried clearing my global environment and running the code again, but that did not work either. I'm not sure what to do about this issue at the moment! Thank you.

**Comment by mikelove** [comment]
Are you reading this line:

> Only for speeding up running the live code chunks in this workflow, we subset to the first 250 genes, representing about one thirtieth of the dataset. This step would not be run in a typical workflow.

https://bioconductor.org/packages/release/workflows/vignettes/rnaseqDTU/inst/doc/rnaseqDTU.html#drimseq

**Comment by pegahabyaneh** [comment]
Yes, I subsetted the data, though I just noticed that my results match those in the workflow from the link you provided, but not those in the workflow from the corresponding article (https://f1000research.com/articles/7-952/v3).

**Comment by mikelove** [comment]
Oh, it’s just because the vignette has to run a bit faster so it has the extra step quoted above.

**Comment by pegahabyaneh** [comment]
I see, thank you!
